import Head from 'next/head'
import Tasks from '@/components/Molecules/Tasks/tasks'

export default function Home() {
  return (
    <>
      <Head>
        <title>Task management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Tasks />
      </main>
    </>
  )
}
